export const PRIMARY_BACKGROUND = '#ffffff'
export const BORDER_RADIUS = '10px'
export const BORDER_BOTTOM_HEADER = '2px solid #386bc2'
export const HEADER_FONT_SIZE = '20px'
export const BODY_FONT_SIZE = '15px'
export const HEADER_FONT_COLOR = '#000000'
export const LOGIN_PADDING = '25px'
export const LIST_FONT_COLOR = '#4f4f4f'